[package]
name = "ntfy"
version = "0.6.0"
edition = "2021"
description = "Library for sending notifications over ntfy"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/shadowylab/ntfy"
repository = "https://github.com/shadowylab/ntfy.git"
readme = "README.md"
keywords = ["ntfy", "notifications", "sdk"]

[dependencies]
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
async-utility = { git = "https://github.com/yukibtc/async-utility", rev = "575b6fb0b4e270ae44208d4b7c234366d33e32f6" }
tokio = { version = "1", features = ["full"] }

[[example]]
name = "blocking"

[[example]]
name = "client"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
