[package]
name = "ntfy"
version = "0.3.3"
edition = "2021"
description = "ntfy rust sdk"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
homepage = "https://github.com/yukibtc/ntfy-sdk"
repository = "https://github.com/yukibtc/ntfy-sdk.git"
readme = "README.md"
keywords = ["ntfy", "notifications", "sdk"]

[features]
default = []
blocking = ["reqwest/blocking"]

[dependencies]
base64 = "0.13"
chrono = "0.4"
log = "0.4"
reqwest = { version = "0.11", features = ["json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "client"

[[example]]
name = "blocking"
required-features = ["blocking"]

[profile.release]
lto = true
codegen-units = 1