[package]
name = "ntfy"
version = "0.1.0"
edition = "2021"
description = "ntfy rust sdk"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
homepage = "https://github.com/yukibtc/ntfy-sdk"
repository = "https://github.com/yukibtc/ntfy-sdk.git"

keywords = ["ntfy", "ntfy.sh", "push notification", "notifications"]

[dependencies]
log = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"