[package]
name = "ntfy"
version = "0.2.0"
edition = "2021"
description = "ntfy rust sdk"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
homepage = "https://github.com/yukibtc/ntfy-sdk"
repository = "https://github.com/yukibtc/ntfy-sdk.git"
keywords = ["ntfy", "notifications", "sdk"]

[features]
default = []
blocking = ["reqwest/blocking"]

[dependencies]
base64 = "0.13"
log = "0.4"
reqwest = { version = "0.11", features = ["json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }