[package]
name = "ntfy"
version = "0.4.0"
edition = "2021"
description = "Library for sending notifications over ntfy"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/shadowylab/ntfy"
repository = "https://github.com/shadowylab/ntfy.git"
readme = "README.md"
keywords = ["ntfy", "notifications", "sdk"]

[features]
default = []
blocking = ["reqwest/blocking"]

[dependencies]
base64 = "0.21"
chrono = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[[example]]
name = "client"

[[example]]
name = "blocking"
required-features = ["blocking"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"