name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-args:
          [
            --no-default-features,
          ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --all -- --config format_code_in_doc_comments=true --check
    - name: Build
      run: cargo build ${{ matrix.build-args }} --all
    - name: Test
      run: cargo test ${{ matrix.build-args }}
    - name: Clippy
      run: cargo clippy ${{ matrix.build-args }} -- -D warnings
